# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
    -   id: detect-private-key

# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.12.5
#     hooks:
#     -   id: ruff
#         args: [--fix]
#     -   id: ruff-format

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
        exclude: |
            (?x)^(
                bpack/tests/test_field_descriptor.py|
                bpack/tests/test_record_descriptor.py|
                bpack/tests/test_utils.py|
                bpack/tests/test_future_annotations.py
            )

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        exclude: tests|examples|data|docs

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.10
    -   id: black-jupyter
        language_version: python3.10

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.17.0
#     hooks:
#     -   id: mypy
#         additional_dependencies:
#         -   tokenize-rt==3.2.0
#         -   numpy>=1.21

-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        additional_dependencies: [tomli]
        exclude: |
            (?x)^(
                docs/spelling_wordlist.txt
            )
