[build-system]
requires = ["setuptools", "wheel"]
build-backend = 'setuptools.build_meta'


[tool.black]
line-length = 79
# target-version = ['py311']

[tool.isort]
profile = "black"
length_sort = true
no_inline_sort = true
include_trailing_comma = true
use_parentheses = true
line_length = 79

