[tox]
env_list =
    py310
    py311
    py312
    py313
    py314
    py314t
    strict
    coverage
    codestyle
    docs
    linkcheck
    spelling
isolated_build = True

[testenv]
description = run the tests with pytest
dependency_groups =
    test
commands =
    python3 -m pytest {tty:--color=yes} --doctest-modules {posargs}

[testenv:strict]
commands =
    python3 -m pytest {tty:--color=yes} -W error {posargs}

[testenv:coverage]
description = run coverage
dependency_groups =
    coverage
commands =
     python3 -m pytest {tty:--color=yes} --cov bpack --cov-report=html --cov-report=term bpack

[testenv:codestyle]
description = run linting
skip_install = true
dependency_groups =
    lint
changedir = {toxinidir}
commands =
    python3 -m flake8 --version
    python3 -m flake8 --count --statistics bpack
	python3 -m pydocstyle --count bpack
	python3 -m isort --check bpack
	python3 -m black --check bpack
	# python3 -m mypy --check-untyped-defs --ignore-missing-imports bpack
    # ruff check bpack
    codespell

[testenv:docs]
description = build docs
allowlist_externals = mkdir
changedir = docs
dependency_groups =
    docs
    alldeps
commands =
    mkdir -p _static
    # python3 -m sphinx -W -b html . _build/html
    # python3 -m sphinx -W -b doctest . _build/doctest
    python3 -m sphinx -b html . _build/html
    python3 -m sphinx -b doctest . _build/doctest

[testenv:linkcheck]
description = linkcheck
allowlist_externals = mkdir
changedir = docs
dependency_groups =
    docs
    alldeps
commands =
    mkdir -p _static
    # python3 -m sphinx -W -b linkcheck . _build/linkcheck
    python3 -m sphinx -b linkcheck . _build/linkcheck

[testenv:spelling]
description = check spelling
allowlist_externals = mkdir
changedir = docs
dependency_groups =
    docs
    alldeps
commands =
    mkdir -p _static
    # python3 -m sphinx -W -b spelling . _build/spelling
    python3 -m sphinx -b spelling . _build/spelling
