name: Docs

on: [push, pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test,docs]
        python -m pip install sphinxcontrib-spelling
    - name: Build docs
      run: |
        mkdir -p docs/_static
        python3 -m sphinx -W -b html docs docs/_build/html
    - name: Link check
      run: |
        mkdir -p docs/_static
        python3 -m sphinx -W -b linkcheck docs docs/_build/linkcheck
    - name: Doctest
      run: |
        mkdir -p docs/_static
        python3 -m sphinx -W -b doctest docs docs/_build/doctest
    - name: Spell check
      run: |
        mkdir -p docs/_static
        python3 -m sphinx -W -b spelling docs docs/_build/spelling
