name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
        python -m pip install flake8 pydocstyle isort black
    - name: Lint with flake8
      run: |
        python -m flake8 --count --show-source --statistics bpack
    - name: Lint with pydocstyle
      run: |
        python -m pydocstyle --count bpack
    - name: Lint with isort
      run: |
        python -m isort --check bpack
    - name: Lint with black
      run: |
        python -m black --check bpack

